// Arayüz metinleri. v2 ile eklenen metinler buradan başlar; v2 sonunda tüm
// metinler bu dosyaya taşınacak (çok dile hazırlık, plan V5).
export const strings = {
  checklist: {
    title: 'Kontrol listesi',
    addPlaceholder: 'Madde ekle',
    itemLabel: title => `Madde: ${title}`,
    deleteItem: title => `"${title}" maddesini sil`,
    progress: (done, total) => `${done}/${total}`,
    progressLabel: (done, total) => `Kontrol listesi: ${done}/${total} tamamlandı`,
  },
  recurrence: {
    title: 'Tekrar',
    none: 'Tekrar yok',
    custom: 'Özel',
    every: 'Her',
    units: { day: 'gün', week: 'hafta', month: 'ay', year: 'yıl' },
    decrease: 'Aralığı azalt',
    increase: 'Aralığı artır',
    intervalLabel: n => `Aralık: ${n}`,
    fromDue: 'Bitiş tarihinden say',
    fromCompletion: 'Tamamlanınca say',
    repeats: label => `Tekrarlıyor: ${label}`,
  },
  reminders: {
    title: 'Hatırlatıcılar',
    options: { 0: 'Zamanında', 10: '10 dk önce', 30: '30 dk önce', 60: '1 saat önce', 1440: '1 gün önce' },
    max: n => `En fazla ${n} hatırlatıcı`,
    untimed: time => `Saat seçilmedi: hatırlatıcılar varsayılan saate (${time}) göre ayarlanır.`,
    permissionDenied: 'Bildirim izni kapalı. Hatırlatıcılar kaydedilir ama bildirim gelmez; izni cihaz ayarlarından açabilirsin.',
    unsupported: 'Bu tarayıcı bildirimleri desteklemiyor; hatırlatıcılar yalnızca uygulama açıkken şerit olarak görünür.',
    webNote: 'Web\'de hatırlatıcılar yalnızca sekme açıkken çalışır.',
    hasReminders: n => `${n} hatırlatıcı`,
    bannerOpen: title => `${title} görevini aç`,
    bannerDismiss: 'Hatırlatıcıyı kapat',
  },
  settings: {
    title: 'Ayarlar',
    open: 'Ayarlar',
    defaultReminderTime: 'Varsayılan hatırlatma saati',
    defaultReminderHelp: 'Saati olmayan görevlerin hatırlatıcıları bu saate göre kurulur.',
    notifications: 'Bildirimler',
    permission: {
      granted: 'Bildirim izni verildi.',
      denied: 'Bildirim izni reddedildi. Cihaz ya da tarayıcı ayarlarından açabilirsin.',
      undetermined: 'Bildirim izni henüz istenmedi.',
      unsupported: 'Bu tarayıcı bildirimleri desteklemiyor.',
    },
    requestPermission: 'Bildirimlere izin ver',
  },
};
